// GENERATED by cf-labs — ambient types for the injected @repo runtime.
// The real implementation is bundled server-side; these stubs are for local
// typechecking only.
declare module '@repo/hmd' {
  export abstract class HMDWorkflow {}
  export class DefaultRollout extends HMDWorkflow {}
  export class FastRollout extends HMDWorkflow {}
  export class HotfixRollout extends HMDWorkflow {}
}

declare module '@repo/ci' {
  export type WorkflowEvent<T> = { payload: T };
  export type CiRemote = 'github' | 'gitlab' | 'cloudflare';
  export type CiParams = {
    installationId: number;
    owner: string;
    repo: string;
    sha: string;
    remote?: CiRemote;
    trigger: 'push' | 'pull_request' | 'tag';
    ref: string;
    branch?: string;
    tag?: string;
    defaultBranch: string;
    pullNumber?: number;
    baseRef?: string;
    beforeSha?: string;
    headCommitMessage?: string;
    actor?: string;
  };
  export type StepConfig = {
    retries?: { limit: number; delay: number; backoff?: 'constant' | 'linear' | 'exponential' };
    timeout?: number;
  };
  export type RunnerOptions = {
    exec: string;
    cwd?: string;
    config?: StepConfig;
    capture?: boolean;
    cloudflareCredentials?: boolean;
    githubToken?: boolean;
    env?: Record<string, string>;
    secrets?: string[];
  };
  export type BuildOptions = {
    worker: string;
    wrangler: string;
    packageManager?: 'pnpm' | 'npm' | 'yarn' | 'bun';
    build?: string;
    services?: string[];
    env?: Record<string, string>;
    secrets?: string[];
    config?: StepConfig;
  };
  export type WorkerBuild = {
    worker: string;
    dir: string;
    deploy(): Promise<{ worker: string; output: string }>;
    preview(): Promise<{ worker: string; scriptName: string; branch: string; url: string }>;
    release(): Promise<
      | { worker: string; workerName: string; versionId: string; firstDeploy: false }
      | { worker: string; workerName: string; firstDeploy: true }
    >;
  };
  export type DeltaCatalogEntry = {
    id: string;
    title: string;
    name: string;
    url: string;
    type?: string;
    selector?: string;
    tags?: string[];
  };
  export type DeltaOptions = (
    | { baseUrl: string; catalog?: never }
    | { catalog: DeltaCatalogEntry[]; baseUrl?: never }
  ) & {
    project?: string;
    baselineBranch?: string;
    maxWaitSeconds?: number;
  };
  export type DeltaBuildStatus =
    | 'pending'
    | 'running'
    | 'success'
    | 'failed'
    | 'cancelled'
    | 'superseded';
  export type DeltaResult = {
    buildId: string;
    project: string;
    reportUrl: string;
    status: DeltaBuildStatus;
    complete: boolean;
    approved: boolean;
    hasRegressions: boolean;
    totalStories: number;
    visualRegressions: number;
    a11yRegressions: number;
    newStories: number;
  };
  export type TestForgeModel =
    | 'claude-sonnet-4-6'
    | '@cf/moonshotai/kimi-k2.7-code'
    | '@cf/google/gemma-4-26b-a4b-it';
  export type TestForgeOptions = {
    url: string;
    project?: string;
    explore?: boolean;
    maxDepth?: number;
    maxPages?: number;
    maxElements?: number;
    customPrompt?: string;
    model?: TestForgeModel;
    maxWaitSeconds?: number;
  };
  export type TestForgeRunPhase =
    | 'queued'
    | 'exploring'
    | 'mapping'
    | 'generating'
    | 'healing'
    | 'done'
    | 'error';
  export type TestForgeSpec = { name: string; status?: 'passed' | 'failed' };
  export type TestForgeRunState = {
    runId: string;
    project: string;
    phase: TestForgeRunPhase;
    complete: boolean;
    error: string | null;
    specs: TestForgeSpec[];
  };
  export type TestForgeResult = TestForgeRunState & { reportUrl: string };
  export type TestForgeRerunOptions = {
    project: string;
    runId: string;
    maxWaitSeconds?: number;
  };
  export type CiCacheRunner = {
    runner(label: string, options: RunnerOptions): Promise<CiRunnerResult>;
  };
  export type CiRunnerResult = {
    exitCode: number;
    output: string;
    logsUrl: string;
    cached?: boolean;
    runner(label: string, options: RunnerOptions): Promise<CiRunnerResult>;
    cache(paths: string[]): CiCacheRunner;
    build(options: BuildOptions): WorkerBuild;
  };
  export type CiRunnerStep = {
    runner(label: string, options: RunnerOptions): Promise<CiRunnerResult>;
    cache(paths: string[]): CiCacheRunner;
    build(options: BuildOptions): WorkerBuild;
    delta(options: DeltaOptions): Promise<DeltaResult>;
    testForge(options: TestForgeOptions): Promise<TestForgeResult>;
    testForgeRerun(options: TestForgeRerunOptions): Promise<TestForgeResult>;
  };
  export abstract class CIWorkflow {
    protected abstract pipeline(
      event: WorkflowEvent<CiParams>,
      step: CiRunnerStep
    ): Promise<void>;
  }
}
